#!/bin/sh

fact(){
  i=1
  total=1
  while [ "$i" -le "$n" ]
  do
    total=$(($total*($i)))
    echo "$i" ":" "$total"
    i=$(($i+1))
  done
  return $total
}
echo "enter n :"
read n
if [ $n > 0 ]
then
	fact $n
else
	echo "error! n must >0"
fi
ret=$?
echo "$ret"
